### PR TITLE
Failed precondition is 412

### PR DESCRIPTION
**Pull request by j-baker**

### CODE REVIEW

**Comment by j-baker** [comment]
Ok. So is there a client side version of the error that'd be appropriate? in this case I want to throw it because the user's used up too many resources server side.

**Comment by uschi2000** [comment]
Could look at adding 413, but you could also do CUSTOM_CLIENT, I guess

**Comment by j-baker** [comment]
yeah, ok. As general feedback, given that this is the name of an actual HTTP response code, we probably should not have used it for one of our error codes with a different name

**Comment by uschi2000** [comment]
Fair. I think copied these from gRPC’s names.

**Pull request closed without merging**
